/**
 * Adherent
 * Adherent api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Account { 
    /**
     * Account state
     */
    actif: boolean;
    /**
     * ID of the account
     */
    id?: number;
    /**
     * Name of the account
     */
    name?: string;
    /**
     * ID of the type of account
     */
    type: number;
}