/**
 * Adherent
 * Adherent api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Device { 
    connectionType: Device.ConnectionTypeEnum;
    ipAddress?: string;
    ipv6Address?: string;
    mac: string;
    username?: string;
}
export namespace Device {
    export type ConnectionTypeEnum = 'wired' | 'wireless';
    export const ConnectionTypeEnum = {
        Wired: 'wired' as ConnectionTypeEnum,
        Wireless: 'wireless' as ConnectionTypeEnum
    };
}