/**
 * Adherent
 * Adherent api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Product { 
    /**
     * Buying price of the product (in cents)
     */
    buyingPriceInCents: number;
    /**
     * ID of the product
     */
    id?: number;
    /**
     * Name of the product
     */
    name: string;
    /**
     * Buying price of the product (in cents)
     */
    sellingPriceInCents: number;
}