/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Product { 
    /**
     * Buying price of the product (in cents)
     */
    buyingPrice: number;
    /**
     * ID of the product
     */
    id?: number;
    /**
     * Name of the product
     */
    name: string;
    /**
     * Buying price of the product (in cents)
     */
    sellingPrice: number;
}

