/**
 * Adherent
 * Adherent api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { PaymentMethod } from './paymentMethod';


export interface Transaction { 
    readonly id?: number;
    name: string;
    readonly src?: Account;
    readonly dst?: Account;
    readonly timestamp?: Date;
    readonly paymentMethod?: PaymentMethod;
    value: number;
    attachments?: string;
    dstID: number;
    srcID: number;
    paymentMethodID: number;
}

