/**
 * Adherent
 * Adherent api
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Transaction { 
    attachements?: string;
    dst: number;
    readonly id?: number;
    name: string;
    product?: number;
    src: number;
    readonly timestamp?: number;
    type: number;
    value: number;
}